### ISSUE TITLE
This is incredible.

### ISSUE THREAD

**Issue by SeraVault** [perfood/couch-auth#81]
Thank you for sharing.  This makes CouchDb usable!  I was looking into how to add a REST "updateProfile" function so that users can update their display name, language, theme, etc...

I'll try and share what I get.

**Comment by LyteFM** [comment]
Thanks for your feedback!

Unfortunately, I don't intend to add a route for that functionality to `couch-auth`. Routes for changing profile information are application specific and should be implemented by developers in their backend using fine-grained controls instead of providing a „one size fits all“ - endpoint.
